//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasketApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Number { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> PresenceID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Presence Presence { get; set; }
        public virtual Student Student { get; set; }
    }
}
